print("Hello im Evelyn!")
input()
name= input("What is your name?")

print(f"Hello{name} nice to meet you!")
input()
print("so lets talk...How about we talk about school")
input()
subject= input("Whats your favorite subject?")
print(f"Cool! {subject} is my favorite to.")
input()
print(f"Why is {subject} your favorite?")
input()
print("Thats really interesting!") 
input()
print(" well... how are you feeling today?")
input()
print("I feel that way to!")
input()
print("Okay so whats your favorite animal?")
input()
print("Mine too!")
input()
print("Well i have to go but i enjoyed talking to you!")